version: '3.9'

services:
  database:
    container_name: guessthegame-database
    image: edgedb/edgedb:1
    restart: 'no'
    environment:
      - EDGEDB_SERVER_SECURITY=insecure_dev_mode
    ports:
      - 8101:5656
    volumes:
      - "./dbschema:/dbschema"
      - "./credentials:/root/.config/edgedb/credentials"

  adminer:
    container_name: guessthegame-adminer
    image: adminer:latest
    restart: 'no'
    depends_on:
      - database
    ports:
      - 8102:8080

volumes:
  guessthegame-database:
