import { INestApplication } from '@nestjs/common'
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger'

/**
 * Bootstrap Swagger documentation server
 * https://docs.nestjs.com/openapi/introduction
 */
export function bootstrapSwagger(app: INestApplication): void {
  const title = 'Guess-The-Game Backend Documentation'
  const description = "OpenAPI documentation auto-generated by Nest.js's swagger pluggin"
  const urlPrefix = 'swagger'
  const apiVersion = process.env.API_VERSION || ''

  const config = new DocumentBuilder()
    .setTitle(title)
    .setDescription(description)
    .setVersion(apiVersion)
    .addBearerAuth()
    .build()

  const document = SwaggerModule.createDocument(app, config)

  SwaggerModule.setup(urlPrefix, app, document, {
    swaggerOptions: {
      persistAuthorization: true,
    },
    customSiteTitle: title,
  })
}
